/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <duktape.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>

/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows to return the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
#define SWIG_ERROR                 (-1)
#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



/* -----------------------------------------------------------------------------
 * dukrun.swg
 *
 * This file contains the runtime support for Duktape modules
 * and includes code for managing global variables and pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#endif

/* -----------------------------------------------------------------------------
 * global swig types
 * ----------------------------------------------------------------------------- */
/* Constant table */
#define SWIG_DUK_INT     1
#define SWIG_DUK_FLOAT   2
#define SWIG_DUK_STRING  3
#define SWIG_DUK_POINTER 4
#define SWIG_DUK_BINARY  5
#define SWIG_DUK_CHAR    6

/* Structure for variable linking table */
typedef struct {
  const char *name;
  duk_c_function get;
  duk_c_function set;
} swig_duk_var_info;

typedef struct swig_duk_method {
  const char *name;
  duk_c_function func;
} swig_duk_method;

/* Constant information structure */
typedef struct {
  int type;
  char *name;
  long lvalue;
  double dvalue;
  void *pvalue;
  swig_type_info **ptype;
} swig_duk_const_info;

typedef struct {
  const char *name;
  duk_c_function getter;
  duk_c_function setter;
} swig_duk_property;

struct swig_duk_class;
/* Can be used to create namespaces. */
typedef struct swig_duk_namespace {
  const char *name;
  duk_function_list_entry *ns_methods;
  swig_duk_property *ns_properties;
  swig_duk_const_info *ns_constants;
  struct swig_duk_class **ns_classes;
  struct swig_duk_namespace **ns_namespaces;
} swig_duk_namespace;

typedef struct swig_duk_class {
  const char *name; /* Name that this class has in Duktape */
  const char *fqname; /* Fully qualified name - Scope + class name */
  swig_type_info   **type;
  duk_c_function  constructor;
  void (*destructor)(void *);
  swig_duk_method   *methods;
  swig_duk_property *properties;
  swig_duk_namespace *cls_static;
  swig_duk_method   *prototype;
  struct swig_duk_class **bases;
  const char **base_names;
} swig_duk_class;

/* this is the struct for wrapping all pointers in SwigDuk
*/
typedef struct {
  swig_type_info   *type;
  bool own;  /* true if owned & must be destroyed */
  void *ptr;
} swig_duk_userdata;

/* this is the struct for wrapping arbitrary packed binary data
(currently it is only used for member function pointers)
the data ordering is similar to swig_duk_userdata, but it is currently not possible
to tell the two structures apart within SWIG, other than by looking at the type
*/
typedef struct {
  swig_type_info   *type;
  bool     own;  /* true if owned & must be destroyed */
  char data[1];  /* arbitary amount of data */    
} swig_duk_rawdata;

SWIGRUNTIME duk_ret_t _wrap_SwigObject_disown(duk_context *ctx)
{
  duk_size_t sz;
  duk_push_this(ctx);
  duk_get_prop_string(ctx, -1, "\FFprivate");
  swig_duk_userdata *udata = (swig_duk_userdata*)duk_to_fixed_buffer(ctx, -1, &sz);
  udata->own = false;
  duk_pop_n(ctx, 2); /* Clean up stack */
  return 0; // undefined
}

SWIGRUNTIME duk_ret_t _wrap_SwigObject_getCPtr(duk_context *ctx)
{
  duk_size_t sz;
  long result;
  duk_push_this(ctx);
  duk_get_prop_string(ctx, -1, "\FFprivate");
  swig_duk_userdata *udata = (swig_duk_userdata*)duk_to_fixed_buffer(ctx, -1, &sz);
  duk_pop_n(ctx, 2);

  result = (long)udata->ptr;
  duk_push_number(ctx, (duk_double_t)result);

  return 1;
}

SWIGRUNTIME duk_ret_t _wrap_SwigObject_equals(duk_context *ctx)
{
  bool result;
  duk_size_t sz1, sz2;

  if(duk_get_top(ctx) != 2) {
    duk_push_string(ctx, "Comparison requires two arguments.");
    duk_throw(ctx);
  }

  duk_get_prop_string(ctx, -1, "\FFprivate");
  swig_duk_userdata *udata = (swig_duk_userdata*)duk_to_fixed_buffer(ctx, -1, &sz1);
  duk_pop(ctx);

  duk_get_prop_string(ctx, -2, "\FFprivate");
  swig_duk_userdata *udata2 = (swig_duk_userdata*)duk_to_fixed_buffer(ctx, -1, &sz2);
  duk_pop(ctx);

  result = (udata->ptr == udata2->ptr);
  duk_push_boolean(ctx, result);

  return 1;
}

SWIGRUNTIME duk_function_list_entry _SwigObject_functions[] = {
  {
    "disown",_wrap_SwigObject_disown, 0
  },
  {
    "equals",_wrap_SwigObject_equals, 2
  },
  {
    "getCPtr",_wrap_SwigObject_getCPtr, 0
  },
  {
    NULL, NULL, 0
  }
};


/* Common SWIG API */
#define SWIG_NewPointerObj(ctx, ptr, type, owner)       SWIG_duk_NewPointerObj(ctx, (void *)ptr, type, owner)
#define SWIG_ConvertPtr(ctx, obj, ptr, type, flags)    SWIG_duk_ConvertPtr(ctx,obj,ptr,type,flags)
#define SWIG_MustGetPtr(ctx, obj, type,flags, argnum,fnname)  SWIG_duk_MustGetPtr(ctx,obj, type,flags, argnum,fnname)
/* for C++ member pointers, ie, member methods */
#define SWIG_ConvertMember(ctx, obj, ptr, sz, ty)       SWIG_duk_ConvertPacked(ctx, obj, ptr, sz, ty)
#define SWIG_NewMemberObj(ctx, ptr, sz, type)      SWIG_duk_NewPackedObj(ctx, ptr, sz, type)

/* Runtime API */
#define SWIG_MODULE_CLIENTDATA_TYPE duk_context*

/* helper #defines */
#define SWIG_fail {goto fail;}
#define SWIG_fail_arg(func_name,argnum,type) \
  {duk_push_sprintf(ctx,"Error in %s (arg %d), expected '%s' got '%s'",\
  func_name,argnum,type,SWIG_duk_typename(ctx,argnum));\
  duk_throw(ctx);}
#define SWIG_fail_ptr(func_name,argnum,type) \
  SWIG_fail_arg(func_name,argnum,(type && type->str)?type->str:"void*")
#define SWIG_check_num_args(func_name,a,b) \
  if (duk_get_top(ctx)<a || duk_get_top(ctx)>b) \
  {duk_push_sprintf(ctx,"Error in %s expected %d..%d args, got %d",func_name,a,b,duk_get_top(ctx));\
  duk_throw(ctx);}

#define SWIG_duk_add_function(ctx,n,f) \
  (duk_pushstring(ctx, n), \
      duk_push_c_function(ctx, f), \
      duk_rawset(ctx,-3))

#define SWIG_duk_add_boolean(ctx,n,b) \
  (duk_push_string(ctx, n), \
  duk_push_boolean(ctx, b)

/* special helper for allowing 'undefined' for usertypes */
#define SWIG_isptrtype(ctx,I) (duk_is_fixed_buffer(ctx,I) || duk_is_undefined(ctx,I))

#define SWIG_exception_fail

/* -----------------------------------------------------------------------------
 * global variable support code
 * ----------------------------------------------------------------------------- */

const char *duk_typename(duk_context *ctx, duk_int_t type) {
  switch(type) {
    case DUK_TYPE_NONE:
      return "Unknown type (invalid index?)";
    case DUK_TYPE_UNDEFINED:
      return "Undefined";
    case DUK_TYPE_NULL:
      return "Null";
    case DUK_TYPE_BOOLEAN:
      return "Boolean";
    case DUK_TYPE_NUMBER:
      return "Number";
    case DUK_TYPE_STRING:
      return "String";
    case DUK_TYPE_OBJECT:
      return "Object";
    case DUK_TYPE_BUFFER:
      return "Buffer";
    case DUK_TYPE_POINTER:
      return "Pointer";
    case DUK_TYPE_LIGHTFUNC:
      return "LightFunc";
  }
  return "Impossible";
}

/* a function to get the typestring of a piece of data */
SWIGRUNTIME const char *SWIG_duk_typename(duk_context *ctx, duk_idx_t idx)
{
  swig_duk_userdata *usr;
  duk_size_t sz;
  if (duk_is_buffer(ctx,idx))
  {
    usr=(swig_duk_userdata*)duk_get_buffer(ctx,idx,&sz);  /* get data */
    if (usr && usr->type && usr->type->str)
      return usr->type->str;
    return "userdata (unknown type)";
  }
  return duk_typename(ctx,duk_get_type(ctx,idx));
}

/* -----------------------------------------------------------------------------
 * global variable support code: classes
 * ----------------------------------------------------------------------------- */

SWIGINTERN duk_ret_t JS_veto_set_variable(duk_context *ctx)
{
  duk_push_string(ctx, "Tried to write read-only variable.");
  duk_throw(ctx);
  return duk_get_top(ctx); /* We should never get here, but stifle warning. */
}

/* 
 * Install properties into an object.
 * This asserts that the target object is on the top of the value stack on entry.
 */
SWIGINTERN void
swig_duk_install_properties(
  duk_context *ctx,
  duk_idx_t obj_idx,
  swig_duk_property *properties)
{
  assert(duk_is_object(ctx, obj_idx)); /* This better be the right object! */
  /* The target object is on top of the value stack after each iteration. */
  for(swig_duk_property *prop = properties; (*prop).name != NULL; prop++) {
    #ifdef SWIGRUNTIME_DEBUG
    printf("Installing property: %s\n", prop->name);
    #endif
    duk_push_string(ctx, prop->name);
    duk_push_c_function(ctx, prop->getter, 0 /* nargs */);
    duk_push_c_function(ctx, prop->setter, 1 /* nargs */);
    duk_def_prop(ctx,obj_idx,DUK_DEFPROP_HAVE_GETTER|DUK_DEFPROP_HAVE_SETTER|DUK_DEFPROP_HAVE_CONFIGURABLE);
  }
}

/* creates the swig registry */
SWIGINTERN void SWIG_duk_create_class_registry(duk_context *ctx)
{
  /* create the SWIG registry object */
  duk_set_top(ctx, 0);
  duk_push_global_stash(ctx);
  duk_push_string(ctx, "registry");
  duk_push_object(ctx);
  duk_put_prop(ctx, -3);
  /* The heap stash is at the top of the value stack now. */
}


/* gets the swig registry (or creates it) */
SWIGINTERN void SWIG_duk_get_class_registry(duk_context *ctx) {
  duk_set_top(ctx, 0);
  duk_push_global_stash(ctx);
  duk_get_prop_string(ctx, -1, "registry");
  if (!duk_is_object(ctx,-1))  /* not there */
  {  /* must be first time, so add it */
    duk_pop_n(ctx,1);  /* remove the result */
    SWIG_duk_create_class_registry(ctx);
    /* then get the class registry */
    duk_get_prop_string(ctx, -1, "registry");
  }
}

/* Helper function to get the classes prototype from the register */
SWIGINTERN void SWIG_duk_get_class_prototype(duk_context *ctx,const char *cname)
{
  SWIG_duk_get_class_registry(ctx);  /* get the registry */
  duk_get_prop_string(ctx, -1, cname);  /* get the name */
}


/* -----------------------------------------------------------------------------
 * Class/structure conversion fns
 * ----------------------------------------------------------------------------- */

/* helper to add prototype to new duk object */
SWIGINTERN void SWIG_duk_AddPrototype(duk_context *ctx,swig_type_info *type)
{
  #ifdef SWIGRUNTIME_DEBUG
  printf("Adding prototype!\n");
  #endif
  if (type->clientdata)  /* there is clientdata: so add the prototype */
  {
    #ifdef SWIGRUNTIME_DEBUG
    printf("Adding prototype %s\n", ((swig_duk_class*)type->clientdata)->fqname);
    #endif
    SWIG_duk_get_class_prototype(ctx,((swig_duk_class*)(type->clientdata))->fqname);
    if (duk_is_object(ctx,-1)) {
      // FIXME
      duk_set_prototype(ctx,-2);
    }
    else
    {
      duk_pop_n(ctx,1);
    }
  }
}

/* pushes a new userdata buffer into the duk stack */
SWIGRUNTIME duk_ret_t SWIG_duk_NewPointerObj(duk_context *ctx,void *ptr,swig_type_info *type,bool own)
{
  duk_size_t sz;
  swig_duk_userdata *usr;
  if (!ptr){
    #ifdef SWIGRUNTIME_DEBUG
    printf("WARNING: NewPointerObj returning a NULL pointer.\n");
    #endif
    duk_push_undefined(ctx);
    return 1;
  }
  usr=(swig_duk_userdata*)duk_push_fixed_buffer(ctx,sizeof(swig_duk_userdata));  /* get data */
  usr->ptr=ptr;  /* set the ptr */
  usr->type=type;
  usr->own=own;
  //SWIG_duk_AddPrototype(ctx,type); /* add prototype */
  return 1;
}

/* takes a object from the duk stack & converts it into an object of the correct type
 (if possible) */
SWIGRUNTIME int SWIG_duk_ConvertPtr(duk_context *ctx,void *object,void **ptr,swig_type_info *type,int flags)
{
  duk_size_t sz;
  swig_duk_userdata *usr;
  swig_cast_info *cast;
  duk_push_heapptr(ctx, object);
  duk_get_prop_string(ctx, -1, "\FFprivate");
  /* special case: duk undefined => NULL pointer */
  if (duk_is_undefined(ctx, -1)){
    #ifdef SWIGRUNTIME_DEBUG
    printf("Converted a NULL pointer.\n");
    #endif
    *ptr=NULL;
    return SWIG_OK;
  }
  usr=(swig_duk_userdata*)duk_to_fixed_buffer(ctx, -1, &sz);  /* get data */
  duk_pop_n(ctx, 2); /* clean up the stack */
  if (usr) {
    if (flags & SWIG_POINTER_DISOWN) {
      /* must disown the object */
      usr->own=0;
    }
    if (!type) {
      /* special cast void*, no casting fn */
      *ptr=usr->ptr;
      return SWIG_OK; /* ok */
    }
    cast=SWIG_TypeCheckStruct(usr->type,type); /* performs normal type checking */
    if (cast) {
      int newmemory = 0;
      *ptr=SWIG_TypeCast(cast,usr->ptr,&newmemory);
      assert(!newmemory); /* newmemory handling not yet implemented */
      return SWIG_OK;  /* ok */
    }
  }
  return SWIG_ERROR;  /* error */
}

/* -----------------------------------------------------------------------------
 * executing Javascript code from within the wrapper
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_DOSTRING_FAIL /* Allows redefining of error function */
#define SWIG_DOSTRING_FAIL(S) fprintf(stderr,"%s\n",S)
#endif
/*
 * Executes a C string in Duktape
 */
SWIGINTERN int 
SWIG_duk_dostring(duk_context *ctx, const char *str) {
  duk_idx_t top, ret;
  if (str==0 || str[0]==0) return 0; /* nothing to do */
  top=duk_get_top(ctx); /* save stack */
  ret = duk_peval_string(ctx, str);
  if (duk_is_eval_error(ctx, ret)) {
    /* Handle eval error */
  }
  duk_set_top(ctx, top); /* restore the stack */
  return 0;
}    

#ifdef __cplusplus
}
#endif

/* ------------------------------ end dukrun.swg  ------------------------------ */


/* -------- TYPES TABLE (BEGIN) -------- */

static swig_type_info *swig_types[1];
static swig_module_info swig_module = {swig_types, 0, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */



namespace swig {
typedef struct{} LANGUAGE_OBJ;
}


extern int    gcd(int x, int y);
extern double Foo;


#define SWIG_duk_INIT example_initialize
#define dukopen_example SWIG_duk_init



static duk_ret_t _wrap_gcd(duk_context *ctx)
{
  /* FRAGMENT: js_function */
  if (duk_get_top(ctx) != 2) {
    duk_push_string(ctx, "Illegal numargs for _wrap_gcd. Expected 2");
    duk_throw(ctx);
  }
  duk_push_this(ctx);
  void *thisObject = duk_get_heapptr(ctx, -1);
  
  int arg1 ;
  int arg2 ;
  int result;
  
  arg1 = (int)duk_to_number(ctx, -0);
  arg2 = (int)duk_to_number(ctx, -1);
  result = (int)gcd(arg1,arg2);
  duk_push_number(ctx, (duk_double_t) result); 
  
  
  return 1;
}


static duk_ret_t _wrap_Foo_set(duk_context *ctx)
{
  /* FRAGMENT: js_setter */
  /* The value must be on the stack top at entry. */
  duk_push_this(ctx);
  void *thisObject = duk_get_heapptr(ctx, -1);
  duk_pop(ctx);
  duk_idx_t value = -1;
  
  double arg1 ;
  
  arg1 = (double)duk_to_number(ctx, value);
  Foo = arg1;
  
  
  return 1;
}


static duk_ret_t _wrap_Foo_get(duk_context *ctx)
{
  /* FRAGMENT: js_getter */
#ifdef SWIGRUNTIME_DEBUG
  printf("Called js_getter _wrap_Foo_get...\n");
#endif
  /* The object must be on the top of the value stack on entry. */
  
  double result;
  
  
  duk_push_this(ctx);
  void *thisObject = duk_get_heapptr(ctx, -1);
  
  result = (double)Foo;
  duk_push_number(ctx, (duk_double_t) result); 
  
  
  return 1;
}


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */


static swig_type_info *swig_type_initial[] = {
  NULL
};


static swig_cast_info *swig_cast_initial[] = {
  NULL
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */



/* FRAGMENT: duk_nspace_declaration */
static swig_duk_property exports_properties[] = {
  /* FRAGMENT: duk_variable_declaration */
  {
    "Foo", _wrap_Foo_get, _wrap_Foo_set
  },
  
  
  {
    NULL, NULL, NULL 
  }
};

static duk_function_list_entry exports_functions[] = {
  /* FRAGMENT: duk_function_declaration */
  {
    "gcd", _wrap_gcd, 2
  },
  
  
  {
    NULL, NULL, 0 
  }
};


SWIGRUNTIME void
SWIG_duk_SetModule(duk_context *ctx, swig_module_info *swig_module) {
  duk_push_heap_stash(ctx);
  duk_push_pointer(ctx, (void *)swig_module);
  duk_put_prop_string(
    ctx,
    -2,
    "swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME
  );
  duk_pop_n(ctx, 1); /* Tidy the stack. */
}

SWIGRUNTIME swig_module_info *
SWIG_duk_GetModule(duk_context *ctx) {
  swig_module_info *ret = NULL;
  duk_push_heap_stash(ctx);
  duk_get_prop_string(
    ctx,
    -1,
    "swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME
  );
  if (duk_is_pointer(ctx,-1))
    ret=(swig_module_info*)duk_get_pointer(ctx,-1);
  duk_pop_n(ctx, 2); /* Tidy the stack. */
  return ret;
}

#define SWIG_GetModule(clientdata)          SWIG_duk_GetModule((duk_context *)clientdata)
#define SWIG_SetModule(clientdata, pointer) SWIG_duk_SetModule((duk_context *)clientdata, pointer)

/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned statically to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif


SWIGRUNTIME void
SWIG_InitializeModule(void *clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int init;

  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }

  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    iter=module_head;
    do {
      if (iter==&swig_module) {
        /* Our module is already in the list, so there's nothing more to do. */
        return;
      }
      iter=iter->next;
    } while (iter!= module_head);

    /* otherwise we must add our module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }

  /* When multiple interpreters are used, a module could have already been initialized in
     a different interpreter, but not yet have a pointer in this interpreter.
     In this case, we do not want to continue adding types... everything should be
     set up already */
  if (init == 0) return;

  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %d\n", swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;

#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
#endif

    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
	type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }

    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {

      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
	if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
	if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
	  printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
	  cast->type = ret;
	  ret = 0;
	} else {
	  /* Check for casting already in the list */
	  swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
	  if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
	  if (!ocast) ret = 0;
	}
      }

      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
	printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
  printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;

  if (init_run) return;
  init_run = 1;

  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
            SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{ /* c-mode */
#endif
}
#endif



#ifdef __cplusplus
extern "C" {
#endif

/* FIXME: return type? */
duk_ret_t swig_duk_init(duk_context *ctx) {
  /* SWIG's internal initialisation */
  SWIG_InitializeModule((void*)ctx);
  SWIG_PropagateClientData();  


// FIXME: Fix by convention in module loader by pushing parent object
duk_push_global_object(ctx);
/* Initialize the base swig type object FIXME */
duk_push_object(ctx);
duk_put_function_list(ctx, -1, _SwigObject_functions);
duk_put_prop_string(ctx, -2, "SWIG");
void *swig_obj_ptr = duk_get_heapptr(ctx, -1);
/* Now the global object is at the stack top.*/
duk_idx_t ns_idx = duk_push_object(ctx);
void *ns_ptr, *exports_ptr = duk_get_heapptr(ctx, -1);
swig_duk_install_properties(ctx, ns_idx, exports_properties);
duk_put_function_list(ctx, ns_idx, exports_functions);
/*
    * By the time we put the property string here, the stack will be...
    * [parent_obj, namespace_obj] 
    * We want to set the property key example in the parent object.
    */
duk_put_prop_string(ctx, -2, "example");
/* Create objects for namespaces */

/* Register classes */


/* Just return the topmost value on the stack, our module. */
return 1;

/* Initialize the base swig type object */
//_SwigObject_objectDefinition.staticFunctions = _SwigObject_functions;
//_SwigObject_objectDefinition.staticValues = _SwigObject_values;
//_SwigObject_classRef = JSClassCreate(&_SwigObject_objectDefinition);

/* Initialize the PackedData class */
//_SwigPackedData_objectDefinition.staticFunctions = _SwigPackedData_functions;
//_SwigPackedData_objectDefinition.staticValues = _SwigPackedData_values;
//_SwigPackedData_objectDefinition.finalize = _wrap_SwigPackedData_delete;
//_SwigPackedData_classRef = JSClassCreate(&_SwigPackedData_objectDefinition);
}
#ifdef __cplusplus
}
#endif

